title: krabx64
description: "krabx64's webpage"
author:
  name: "krabx64"
  email: ""
  url: "https://github.com/krabx64"

baseurl: ""

source: .
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: /blog/page:num/

collections:
  posts:
    output: true
  lifestyle:  # category added
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"  # Default layout for posts

  - scope:
      path: ""
      type: "lifestyle"  # Default layout for category
    values:
      layout: "lifestyle"  # Specify the layout for category

# Custom variables
owner: "krab"
year: "2023"

# Thanks tocttou for this theme
remote_theme: tocttou/hacker-blog

# Jekyll serve options
port: 8880  # local server port
